### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by fjsr-py** [icebeam7/VideoAnalyzer#1]
Hi there! I recommend you to add a MIT license to your Project. If you need help, I can help you with it.

**Comment by icebeam7** [comment]
Sure thing. Go ahead! Thank you for your interest :-)

**Comment by fjsr-py** [comment]
The license has been added to the proyect.

**Comment by icebeam7** [comment]
Thanks a lot for your help! I'm closing the issue as it has been completed :)
